@extends('page')

@section('content')

    <div>

        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#community" aria-controls="home" role="tab" data-toggle="tab">
                    Community
                </a>
            </li>
            <li role="presentation">
                <a href="#dirt-rally" aria-controls="home" role="tab" data-toggle="tab">
                    Dirt Rally
                </a>
            </li>
            <li role="presentation">
                <a href="#assetto-corsa" aria-controls="profile" role="tab" data-toggle="tab">
                    Assetto Corsa
                </a>
            </li>
            <li role="presentation">
                <a href="#site" aria-controls="profile" role="tab" data-toggle="tab">
                    This Site
                </a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="community">
                <p>
                    The Conelanders community has been set up by <strong>ConeDodger</strong> for fans of himself and
                    <strong>KurtJMac</strong>.
                </p>
                <p>
                    ConeDodger has set up and managed all events, and puts up with everyone else trying to make his life
                    complicated.
                </p>
            </div>
            <div role="tabpanel" class="tab-pane" id="dirt-rally">
                <p>
                    Dirt Rally results are pulled in automatically from the <a href="https://www.dirtgame.com">dirtgame.com</a>
                    website. This runs on a 3-hour schedule, and does an extra pull of results a few minutes before an event
                    is due to close - in case the results completely dissappear when the event ends (which they do on the
                    league webpage, but we can sometimes get them for a short while afterwards.
                </p>
                <p>
                    The points system was created by <strong>Georgin</strong>, which I have brought across.
                </p>
                <p>
                    The only manual steps are to add new championships, seasons, and events.
                </p>
            </div>
            <div role="tabpanel" class="tab-pane" id="assetto-corsa">
                <p>
                    Assetto Corsa results are generated by uploading the <em>json</em> results file from the server.
                    <strong>Th3HolyMoose</strong> wrote a script to parse the file and get the results, which then
                    feeds into the website for displaying.
                </p>
                <p>
                    The colours for the driver numbers should be representative of the car colours used in-game, but
                    if the in-game colours don't make for a legible number, they are tweaked.
                </p>
                <p>
                    The gray background on the lap charts denotes when a driver has been lapped. However, the server
                    lets everyone finish the whole race (not just the lap they're on once the leader finishes), so
                    they look a little weird at the end.
                </p>
            </div>
            <div role="tabpanel" class="tab-pane" id="site">
                <p>
                    This site has been developed by <strong>dJomp</strong>.
                </p>
                <p>
                    If you find anything amiss, or have any suggestions, you should contact him; he's on
                    <a href="https://www.reddit.com/user/djomp">reddit</a>,
                    <a href="https://www.twitter.com/djomp">twitter</a>, and
                    <a href="https://www.discordapp.com">discord</a>
                    under the same username.
                </p>
            </div>
        </div>

    </div>

    <script type="text/javascript">
        $('#driverTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    </script>

@endsection